//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

var outputFile = flag.String("o", "", "output `file`")

func main() {
	flag.Parse()

	b := new(bytes.Buffer)
	b.WriteString(`// Code generated by the gen_tmpls.go script; DO NOT EDIT.

package notify

import htmltmpl "html/template"
`)

	names, err := filepath.Glob(flag.Arg(0))
	if err != nil {
		log.Fatal(err)
	}

	for _, name := range names {
		if strings.HasSuffix(name, ".html") {
			if err := addHTMLTmpl(b, name); err != nil {
				log.Fatalf("adding %q: %v", name, err)
			}
		}
	}

	if err := os.WriteFile(*outputFile, b.Bytes(), 0644); err != nil {
		log.Fatal(err)
	}
}

func addHTMLTmpl(b *bytes.Buffer, tmplname string) error {
	varName := filepath.Base(tmplname)
	if i := strings.Index(varName, "."); i > 0 {
		varName = varName[:i] + "HTML"
	}

	tmpl, err := os.ReadFile(tmplname)
	if err != nil {
		return err
	}

	if bytes.ContainsRune(tmpl, '`') {
		return fmt.Errorf("cannot contain backtick")
	}

	fmt.Fprintf(b, "\nvar %s = htmltmpl.Must(htmltmpl.New(\"email\").Parse(`%s`))\n", varName, tmpl)
	return nil
}
